//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}naglowek"/>
 *         &lt;element ref="{http://www.kedi}pozycje"/>
 *         &lt;element ref="{http://www.kedi}podsumowanie"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naglowek",
    "pozycje",
    "podsumowanie"
})
@XmlRootElement(name = "faktura")
public class Faktura {

    @XmlElement(required = true)
    protected Naglowek naglowek;
    @XmlElement(required = true)
    protected Pozycje pozycje;
    @XmlElement(required = true)
    protected Podsumowanie podsumowanie;

    /**
     * Gets the value of the naglowek property.
     * 
     * @return
     *     possible object is
     *     {@link Naglowek }
     *     
     */
    public Naglowek getNaglowek() {
        return naglowek;
    }

    /**
     * Sets the value of the naglowek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Naglowek }
     *     
     */
    public void setNaglowek(Naglowek value) {
        this.naglowek = value;
    }

    /**
     * Gets the value of the pozycje property.
     * 
     * @return
     *     possible object is
     *     {@link Pozycje }
     *     
     */
    public Pozycje getPozycje() {
        return pozycje;
    }

    /**
     * Sets the value of the pozycje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pozycje }
     *     
     */
    public void setPozycje(Pozycje value) {
        this.pozycje = value;
    }

    /**
     * Gets the value of the podsumowanie property.
     * 
     * @return
     *     possible object is
     *     {@link Podsumowanie }
     *     
     */
    public Podsumowanie getPodsumowanie() {
        return podsumowanie;
    }

    /**
     * Sets the value of the podsumowanie property.
     * 
     * @param value
     *     allowed object is
     *     {@link Podsumowanie }
     *     
     */
    public void setPodsumowanie(Podsumowanie value) {
        this.podsumowanie = value;
    }

}
