//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}wersja"/>
 *         &lt;element ref="{http://www.kedi}data-utworzenia"/>
 *         &lt;element ref="{http://www.kedi}copyright"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "info")
public class Info {

    @XmlElement(required = true)
    protected String wersja;
    @XmlElement(name = "data-utworzenia", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataUtworzenia;
    @XmlElement(required = true)
    protected String copyright;

    /**
     * Gets the value of the wersja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWersja() {
        return wersja;
    }

    /**
     * Sets the value of the wersja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWersja(String value) {
        this.wersja = value;
    }

    /**
     * Gets the value of the dataUtworzenia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataUtworzenia() {
        return dataUtworzenia;
    }

    /**
     * Sets the value of the dataUtworzenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataUtworzenia(XMLGregorianCalendar value) {
        this.dataUtworzenia = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

}
