//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.kedi}konta"/>
 *         &lt;element ref="{http://www.kedi}id-knt"/>
 *         &lt;element ref="{http://www.kedi}id-knt-ks"/>
 *         &lt;element ref="{http://www.kedi}nazwa"/>
 *         &lt;element ref="{http://www.kedi}nip"/>
 *         &lt;element ref="{http://www.kedi}ulica"/>
 *         &lt;element ref="{http://www.kedi}regon"/>
 *         &lt;element ref="{http://www.kedi}nr-domu"/>
 *         &lt;element ref="{http://www.kedi}nr-lokalu"/>
 *         &lt;element ref="{http://www.kedi}kod-pocztowy"/>
 *         &lt;element ref="{http://www.kedi}miejscowosc"/>
 *         &lt;element ref="{http://www.kedi}kraj"/>
 *         &lt;element ref="{http://www.kedi}telefon"/>
 *         &lt;element ref="{http://www.kedi}fax"/>
 *         &lt;element ref="{http://www.kedi}email"/>
 *         &lt;element ref="{http://www.kedi}zezwolenie"/>
 *         &lt;element ref="{http://www.kedi}bank-nazwa"/>
 *         &lt;element ref="{http://www.kedi}bank-nr-konta"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kontaOrIdKntOrIdKntKs"
})
@XmlRootElement(name = "kontrahent")
public class Kontrahent {

    @XmlElementRefs({
        @XmlElementRef(name = "nr-lokalu", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "email", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "telefon", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "id-knt", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "kraj", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "zezwolenie", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bank-nazwa", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nr-domu", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "kod-pocztowy", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "miejscowosc", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fax", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bank-nr-konta", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nazwa", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nip", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ulica", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "konta", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "regon", namespace = "http://www.kedi", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "id-knt-ks", namespace = "http://www.kedi", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> kontaOrIdKntOrIdKntKs;

    /**
     * Gets the value of the kontaOrIdKntOrIdKntKs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kontaOrIdKntOrIdKntKs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKontaOrIdKntOrIdKntKs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Short }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getKontaOrIdKntOrIdKntKs() {
        if (kontaOrIdKntOrIdKntKs == null) {
            kontaOrIdKntOrIdKntKs = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.kontaOrIdKntOrIdKntKs;
    }

}
