//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}czy-duplikat"/>
 *         &lt;element ref="{http://www.kedi}data-wystawienia"/>
 *         &lt;element ref="{http://www.kedi}data-sprzedazy"/>
 *         &lt;element ref="{http://www.kedi}id-knt-sprzedawcy"/>
 *         &lt;element ref="{http://www.kedi}id-knt-nabywcy"/>
 *         &lt;element ref="{http://www.kedi}termin-platnosci"/>
 *         &lt;element ref="{http://www.kedi}nr-faktury"/>
 *         &lt;element ref="{http://www.kedi}typ-faktury"/>
 *         &lt;element ref="{http://www.kedi}id-faktury"/>
 *         &lt;element ref="{http://www.kedi}uwagi"/>
 *         &lt;element ref="{http://www.kedi}gid"/>
 *         &lt;element ref="{http://www.kedi}nr-rezerwacji"/>
 *         &lt;element ref="{http://www.kedi}wartosc-netto"/>
 *         &lt;element ref="{http://www.kedi}wartosc-brutto-slownie"/>
 *         &lt;element ref="{http://www.kedi}wartosc-brutto"/>
 *         &lt;element ref="{http://www.kedi}wartosc-vat"/>
 *         &lt;element ref="{http://www.kedi}forma-platnosci"/>
 *         &lt;element ref="{http://www.kedi}czy-korekta"/>
 *         &lt;element ref="{http://www.kedi}liczba-poz"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "naglowek")
public class Naglowek {

    @XmlElement(name = "czy-duplikat", required = true)
    protected String czyDuplikat;
    @XmlElement(name = "data-wystawienia", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataWystawienia;
    @XmlElement(name = "data-sprzedazy", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataSprzedazy;
    @XmlElement(name = "id-knt-sprzedawcy")
    protected short idKntSprzedawcy;
    @XmlElement(name = "id-knt-nabywcy")
    protected short idKntNabywcy;
    @XmlElement(name = "termin-platnosci", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar terminPlatnosci;
    @XmlElement(name = "nr-faktury", required = true)
    protected String nrFaktury;
    @XmlElement(name = "typ-faktury", required = true)
    protected String typFaktury;
    @XmlElement(name = "id-faktury")
    protected int idFaktury;
    @XmlElement(required = true)
    protected String uwagi;
    @XmlElement(required = true)
    protected String gid;
    @XmlElement(name = "nr-rezerwacji", required = true)
    protected String nrRezerwacji;
    @XmlElement(name = "wartosc-netto")
    protected float wartoscNetto;
    @XmlElement(name = "wartosc-brutto-slownie", required = true)
    protected String wartoscBruttoSlownie;
    @XmlElement(name = "wartosc-brutto")
    protected float wartoscBrutto;
    @XmlElement(name = "wartosc-vat")
    protected float wartoscVat;
    @XmlElement(name = "forma-platnosci", required = true)
    protected String formaPlatnosci;
    @XmlElement(name = "czy-korekta", required = true)
    protected String czyKorekta;
    @XmlElement(name = "liczba-poz")
    protected byte liczbaPoz;

    /**
     * Gets the value of the czyDuplikat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCzyDuplikat() {
        return czyDuplikat;
    }

    /**
     * Sets the value of the czyDuplikat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCzyDuplikat(String value) {
        this.czyDuplikat = value;
    }

    /**
     * Gets the value of the dataWystawienia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataWystawienia() {
        return dataWystawienia;
    }

    /**
     * Sets the value of the dataWystawienia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataWystawienia(XMLGregorianCalendar value) {
        this.dataWystawienia = value;
    }

    /**
     * Gets the value of the dataSprzedazy property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataSprzedazy() {
        return dataSprzedazy;
    }

    /**
     * Sets the value of the dataSprzedazy property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataSprzedazy(XMLGregorianCalendar value) {
        this.dataSprzedazy = value;
    }

    /**
     * Gets the value of the idKntSprzedawcy property.
     * 
     */
    public short getIdKntSprzedawcy() {
        return idKntSprzedawcy;
    }

    /**
     * Sets the value of the idKntSprzedawcy property.
     * 
     */
    public void setIdKntSprzedawcy(short value) {
        this.idKntSprzedawcy = value;
    }

    /**
     * Gets the value of the idKntNabywcy property.
     * 
     */
    public short getIdKntNabywcy() {
        return idKntNabywcy;
    }

    /**
     * Sets the value of the idKntNabywcy property.
     * 
     */
    public void setIdKntNabywcy(short value) {
        this.idKntNabywcy = value;
    }

    /**
     * Gets the value of the terminPlatnosci property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTerminPlatnosci() {
        return terminPlatnosci;
    }

    /**
     * Sets the value of the terminPlatnosci property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTerminPlatnosci(XMLGregorianCalendar value) {
        this.terminPlatnosci = value;
    }

    /**
     * Gets the value of the nrFaktury property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrFaktury() {
        return nrFaktury;
    }

    /**
     * Sets the value of the nrFaktury property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrFaktury(String value) {
        this.nrFaktury = value;
    }

    /**
     * Gets the value of the typFaktury property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypFaktury() {
        return typFaktury;
    }

    /**
     * Sets the value of the typFaktury property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypFaktury(String value) {
        this.typFaktury = value;
    }

    /**
     * Gets the value of the idFaktury property.
     * 
     */
    public int getIdFaktury() {
        return idFaktury;
    }

    /**
     * Sets the value of the idFaktury property.
     * 
     */
    public void setIdFaktury(int value) {
        this.idFaktury = value;
    }

    /**
     * Gets the value of the uwagi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUwagi() {
        return uwagi;
    }

    /**
     * Sets the value of the uwagi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUwagi(String value) {
        this.uwagi = value;
    }

    /**
     * Gets the value of the gid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGid() {
        return gid;
    }

    /**
     * Sets the value of the gid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGid(String value) {
        this.gid = value;
    }

    /**
     * Gets the value of the nrRezerwacji property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrRezerwacji() {
        return nrRezerwacji;
    }

    /**
     * Sets the value of the nrRezerwacji property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrRezerwacji(String value) {
        this.nrRezerwacji = value;
    }

    /**
     * Gets the value of the wartoscNetto property.
     * 
     */
    public float getWartoscNetto() {
        return wartoscNetto;
    }

    /**
     * Sets the value of the wartoscNetto property.
     * 
     */
    public void setWartoscNetto(float value) {
        this.wartoscNetto = value;
    }

    /**
     * Gets the value of the wartoscBruttoSlownie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWartoscBruttoSlownie() {
        return wartoscBruttoSlownie;
    }

    /**
     * Sets the value of the wartoscBruttoSlownie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWartoscBruttoSlownie(String value) {
        this.wartoscBruttoSlownie = value;
    }

    /**
     * Gets the value of the wartoscBrutto property.
     * 
     */
    public float getWartoscBrutto() {
        return wartoscBrutto;
    }

    /**
     * Sets the value of the wartoscBrutto property.
     * 
     */
    public void setWartoscBrutto(float value) {
        this.wartoscBrutto = value;
    }

    /**
     * Gets the value of the wartoscVat property.
     * 
     */
    public float getWartoscVat() {
        return wartoscVat;
    }

    /**
     * Sets the value of the wartoscVat property.
     * 
     */
    public void setWartoscVat(float value) {
        this.wartoscVat = value;
    }

    /**
     * Gets the value of the formaPlatnosci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaPlatnosci() {
        return formaPlatnosci;
    }

    /**
     * Sets the value of the formaPlatnosci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaPlatnosci(String value) {
        this.formaPlatnosci = value;
    }

    /**
     * Gets the value of the czyKorekta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCzyKorekta() {
        return czyKorekta;
    }

    /**
     * Sets the value of the czyKorekta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCzyKorekta(String value) {
        this.czyKorekta = value;
    }

    /**
     * Gets the value of the liczbaPoz property.
     * 
     */
    public byte getLiczbaPoz() {
        return liczbaPoz;
    }

    /**
     * Sets the value of the liczbaPoz property.
     * 
     */
    public void setLiczbaPoz(byte value) {
        this.liczbaPoz = value;
    }

}
