//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}id-poz-faktury"/>
 *         &lt;element ref="{http://www.kedi}nr-poz-faktury"/>
 *         &lt;element ref="{http://www.kedi}id-towaru"/>
 *         &lt;element ref="{http://www.kedi}rodzaj-ceny"/>
 *         &lt;element ref="{http://www.kedi}cena-netto-bu"/>
 *         &lt;element ref="{http://www.kedi}cena-netto"/>
 *         &lt;element ref="{http://www.kedi}cena-brutto-bu"/>
 *         &lt;element ref="{http://www.kedi}cena-brutto"/>
 *         &lt;element ref="{http://www.kedi}ilosc"/>
 *         &lt;element ref="{http://www.kedi}jednostka-miary"/>
 *         &lt;element ref="{http://www.kedi}stawka-vat"/>
 *         &lt;element ref="{http://www.kedi}wartosc-vat"/>
 *         &lt;element ref="{http://www.kedi}wartosc-vat-bu"/>
 *         &lt;element ref="{http://www.kedi}wartosc-brutto"/>
 *         &lt;element ref="{http://www.kedi}wartosc-netto"/>
 *         &lt;element ref="{http://www.kedi}cena-detal-brutto"/>
 *         &lt;element ref="{http://www.kedi}data-waznosci"/>
 *         &lt;element ref="{http://www.kedi}seria"/>
 *         &lt;element ref="{http://www.kedi}kod-kreskowy"/>
 *         &lt;element ref="{http://www.kedi}upust"/>
 *         &lt;element ref="{http://www.kedi}upust-kwota"/>
 *         &lt;element ref="{http://www.kedi}wytworca-nazwa"/>
 *         &lt;element ref="{http://www.kedi}wytworca-kraj"/>
 *         &lt;element ref="{http://www.kedi}pkwiu"/>
 *         &lt;element ref="{http://www.kedi}zrodla-poz-faktury"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "pozycja")
public class Pozycja {

    @XmlElement(name = "id-poz-faktury")
    protected int idPozFaktury;
    @XmlElement(name = "nr-poz-faktury")
    protected byte nrPozFaktury;
    @XmlElement(name = "id-towaru")
    protected int idTowaru;
    @XmlElement(name = "rodzaj-ceny", required = true)
    protected String rodzajCeny;
    @XmlElement(name = "cena-netto-bu")
    protected float cenaNettoBu;
    @XmlElement(name = "cena-netto")
    protected float cenaNetto;
    @XmlElement(name = "cena-brutto-bu")
    protected float cenaBruttoBu;
    @XmlElement(name = "cena-brutto")
    protected float cenaBrutto;
    protected float ilosc;
    @XmlElement(name = "jednostka-miary", required = true)
    protected String jednostkaMiary;
    @XmlElement(name = "stawka-vat")
    protected float stawkaVat;
    @XmlElement(name = "wartosc-vat")
    protected float wartoscVat;
    @XmlElement(name = "wartosc-vat-bu")
    protected float wartoscVatBu;
    @XmlElement(name = "wartosc-brutto")
    protected float wartoscBrutto;
    @XmlElement(name = "wartosc-netto")
    protected float wartoscNetto;
    @XmlElement(name = "cena-detal-brutto")
    protected float cenaDetalBrutto;
    @XmlElement(name = "data-waznosci", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataWaznosci;
    @XmlElement(required = true)
    protected String seria;
    @XmlElement(name = "kod-kreskowy")
    protected long kodKreskowy;
    protected float upust;
    @XmlElement(name = "upust-kwota")
    protected float upustKwota;
    @XmlElement(name = "wytworca-nazwa", required = true)
    protected String wytworcaNazwa;
    @XmlElement(name = "wytworca-kraj", required = true)
    protected String wytworcaKraj;
    @XmlElement(required = true)
    protected String pkwiu;
    @XmlElement(name = "zrodla-poz-faktury", required = true)
    protected ZrodlaPozFaktury zrodlaPozFaktury;

    /**
     * Gets the value of the idPozFaktury property.
     * 
     */
    public int getIdPozFaktury() {
        return idPozFaktury;
    }

    /**
     * Sets the value of the idPozFaktury property.
     * 
     */
    public void setIdPozFaktury(int value) {
        this.idPozFaktury = value;
    }

    /**
     * Gets the value of the nrPozFaktury property.
     * 
     */
    public byte getNrPozFaktury() {
        return nrPozFaktury;
    }

    /**
     * Sets the value of the nrPozFaktury property.
     * 
     */
    public void setNrPozFaktury(byte value) {
        this.nrPozFaktury = value;
    }

    /**
     * Gets the value of the idTowaru property.
     * 
     */
    public int getIdTowaru() {
        return idTowaru;
    }

    /**
     * Sets the value of the idTowaru property.
     * 
     */
    public void setIdTowaru(int value) {
        this.idTowaru = value;
    }

    /**
     * Gets the value of the rodzajCeny property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRodzajCeny() {
        return rodzajCeny;
    }

    /**
     * Sets the value of the rodzajCeny property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRodzajCeny(String value) {
        this.rodzajCeny = value;
    }

    /**
     * Gets the value of the cenaNettoBu property.
     * 
     */
    public float getCenaNettoBu() {
        return cenaNettoBu;
    }

    /**
     * Sets the value of the cenaNettoBu property.
     * 
     */
    public void setCenaNettoBu(float value) {
        this.cenaNettoBu = value;
    }

    /**
     * Gets the value of the cenaNetto property.
     * 
     */
    public float getCenaNetto() {
        return cenaNetto;
    }

    /**
     * Sets the value of the cenaNetto property.
     * 
     */
    public void setCenaNetto(float value) {
        this.cenaNetto = value;
    }

    /**
     * Gets the value of the cenaBruttoBu property.
     * 
     */
    public float getCenaBruttoBu() {
        return cenaBruttoBu;
    }

    /**
     * Sets the value of the cenaBruttoBu property.
     * 
     */
    public void setCenaBruttoBu(float value) {
        this.cenaBruttoBu = value;
    }

    /**
     * Gets the value of the cenaBrutto property.
     * 
     */
    public float getCenaBrutto() {
        return cenaBrutto;
    }

    /**
     * Sets the value of the cenaBrutto property.
     * 
     */
    public void setCenaBrutto(float value) {
        this.cenaBrutto = value;
    }

    /**
     * Gets the value of the ilosc property.
     * 
     */
    public float getIlosc() {
        return ilosc;
    }

    /**
     * Sets the value of the ilosc property.
     * 
     */
    public void setIlosc(float value) {
        this.ilosc = value;
    }

    /**
     * Gets the value of the jednostkaMiary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJednostkaMiary() {
        return jednostkaMiary;
    }

    /**
     * Sets the value of the jednostkaMiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJednostkaMiary(String value) {
        this.jednostkaMiary = value;
    }

    /**
     * Gets the value of the stawkaVat property.
     * 
     */
    public float getStawkaVat() {
        return stawkaVat;
    }

    /**
     * Sets the value of the stawkaVat property.
     * 
     */
    public void setStawkaVat(float value) {
        this.stawkaVat = value;
    }

    /**
     * Gets the value of the wartoscVat property.
     * 
     */
    public float getWartoscVat() {
        return wartoscVat;
    }

    /**
     * Sets the value of the wartoscVat property.
     * 
     */
    public void setWartoscVat(float value) {
        this.wartoscVat = value;
    }

    /**
     * Gets the value of the wartoscVatBu property.
     * 
     */
    public float getWartoscVatBu() {
        return wartoscVatBu;
    }

    /**
     * Sets the value of the wartoscVatBu property.
     * 
     */
    public void setWartoscVatBu(float value) {
        this.wartoscVatBu = value;
    }

    /**
     * Gets the value of the wartoscBrutto property.
     * 
     */
    public float getWartoscBrutto() {
        return wartoscBrutto;
    }

    /**
     * Sets the value of the wartoscBrutto property.
     * 
     */
    public void setWartoscBrutto(float value) {
        this.wartoscBrutto = value;
    }

    /**
     * Gets the value of the wartoscNetto property.
     * 
     */
    public float getWartoscNetto() {
        return wartoscNetto;
    }

    /**
     * Sets the value of the wartoscNetto property.
     * 
     */
    public void setWartoscNetto(float value) {
        this.wartoscNetto = value;
    }

    /**
     * Gets the value of the cenaDetalBrutto property.
     * 
     */
    public float getCenaDetalBrutto() {
        return cenaDetalBrutto;
    }

    /**
     * Sets the value of the cenaDetalBrutto property.
     * 
     */
    public void setCenaDetalBrutto(float value) {
        this.cenaDetalBrutto = value;
    }

    /**
     * Gets the value of the dataWaznosci property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataWaznosci() {
        return dataWaznosci;
    }

    /**
     * Sets the value of the dataWaznosci property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataWaznosci(XMLGregorianCalendar value) {
        this.dataWaznosci = value;
    }

    /**
     * Gets the value of the seria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeria() {
        return seria;
    }

    /**
     * Sets the value of the seria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeria(String value) {
        this.seria = value;
    }

    /**
     * Gets the value of the kodKreskowy property.
     * 
     */
    public long getKodKreskowy() {
        return kodKreskowy;
    }

    /**
     * Sets the value of the kodKreskowy property.
     * 
     */
    public void setKodKreskowy(long value) {
        this.kodKreskowy = value;
    }

    /**
     * Gets the value of the upust property.
     * 
     */
    public float getUpust() {
        return upust;
    }

    /**
     * Sets the value of the upust property.
     * 
     */
    public void setUpust(float value) {
        this.upust = value;
    }

    /**
     * Gets the value of the upustKwota property.
     * 
     */
    public float getUpustKwota() {
        return upustKwota;
    }

    /**
     * Sets the value of the upustKwota property.
     * 
     */
    public void setUpustKwota(float value) {
        this.upustKwota = value;
    }

    /**
     * Gets the value of the wytworcaNazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWytworcaNazwa() {
        return wytworcaNazwa;
    }

    /**
     * Sets the value of the wytworcaNazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWytworcaNazwa(String value) {
        this.wytworcaNazwa = value;
    }

    /**
     * Gets the value of the wytworcaKraj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWytworcaKraj() {
        return wytworcaKraj;
    }

    /**
     * Sets the value of the wytworcaKraj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWytworcaKraj(String value) {
        this.wytworcaKraj = value;
    }

    /**
     * Gets the value of the pkwiu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkwiu() {
        return pkwiu;
    }

    /**
     * Sets the value of the pkwiu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkwiu(String value) {
        this.pkwiu = value;
    }

    /**
     * Gets the value of the zrodlaPozFaktury property.
     * 
     * @return
     *     possible object is
     *     {@link ZrodlaPozFaktury }
     *     
     */
    public ZrodlaPozFaktury getZrodlaPozFaktury() {
        return zrodlaPozFaktury;
    }

    /**
     * Sets the value of the zrodlaPozFaktury property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZrodlaPozFaktury }
     *     
     */
    public void setZrodlaPozFaktury(ZrodlaPozFaktury value) {
        this.zrodlaPozFaktury = value;
    }

}
