//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}stawka"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stawka"
})
@XmlRootElement(name = "stawki")
public class Stawki {

    @XmlElement(required = true)
    protected Stawka stawka;

    /**
     * Gets the value of the stawka property.
     * 
     * @return
     *     possible object is
     *     {@link Stawka }
     *     
     */
    public Stawka getStawka() {
        return stawka;
    }

    /**
     * Sets the value of the stawka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stawka }
     *     
     */
    public void setStawka(Stawka value) {
        this.stawka = value;
    }

}
