//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}stawka-vat"/>
 *         &lt;element ref="{http://www.kedi}wartosc-vat"/>
 *         &lt;element ref="{http://www.kedi}wartosc-netto"/>
 *         &lt;element ref="{http://www.kedi}wartosc-brutto"/>
 *         &lt;element ref="{http://www.kedi}opis"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "stawka")
public class Stawka {

    @XmlElement(name = "stawka-vat")
    protected float stawkaVat;
    @XmlElement(name = "wartosc-vat")
    protected float wartoscVat;
    @XmlElement(name = "wartosc-netto")
    protected float wartoscNetto;
    @XmlElement(name = "wartosc-brutto")
    protected float wartoscBrutto;
    @XmlElement(required = true)
    protected String opis;

    /**
     * Gets the value of the stawkaVat property.
     * 
     */
    public float getStawkaVat() {
        return stawkaVat;
    }

    /**
     * Sets the value of the stawkaVat property.
     * 
     */
    public void setStawkaVat(float value) {
        this.stawkaVat = value;
    }

    /**
     * Gets the value of the wartoscVat property.
     * 
     */
    public float getWartoscVat() {
        return wartoscVat;
    }

    /**
     * Sets the value of the wartoscVat property.
     * 
     */
    public void setWartoscVat(float value) {
        this.wartoscVat = value;
    }

    /**
     * Gets the value of the wartoscNetto property.
     * 
     */
    public float getWartoscNetto() {
        return wartoscNetto;
    }

    /**
     * Sets the value of the wartoscNetto property.
     * 
     */
    public void setWartoscNetto(float value) {
        this.wartoscNetto = value;
    }

    /**
     * Gets the value of the wartoscBrutto property.
     * 
     */
    public float getWartoscBrutto() {
        return wartoscBrutto;
    }

    /**
     * Sets the value of the wartoscBrutto property.
     * 
     */
    public void setWartoscBrutto(float value) {
        this.wartoscBrutto = value;
    }

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpis(String value) {
        this.opis = value;
    }

}
