//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}id-towaru"/>
 *         &lt;element ref="{http://www.kedi}id-towaru-ks"/>
 *         &lt;element ref="{http://www.kedi}nazwa"/>
 *         &lt;element ref="{http://www.kedi}postac"/>
 *         &lt;element ref="{http://www.kedi}dawka"/>
 *         &lt;element ref="{http://www.kedi}opakowanie"/>
 *         &lt;element ref="{http://www.kedi}stawka-vat"/>
 *         &lt;element ref="{http://www.kedi}pkwiu"/>
 *         &lt;element ref="{http://www.kedi}podmiot-odpowiedzialny-nazwa"/>
 *         &lt;element ref="{http://www.kedi}podmiot-odpowiedzialny-kraj"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "towar")
public class Towar {

    @XmlElement(name = "id-towaru")
    protected int idTowaru;
    @XmlElement(name = "id-towaru-ks")
    protected int idTowaruKs;
    @XmlElement(required = true)
    protected String nazwa;
    @XmlElement(required = true)
    protected String postac;
    @XmlElement(required = true)
    protected String dawka;
    @XmlElement(required = true)
    protected String opakowanie;
    @XmlElement(name = "stawka-vat")
    protected float stawkaVat;
    @XmlElement(required = true)
    protected String pkwiu;
    @XmlElement(name = "podmiot-odpowiedzialny-nazwa", required = true)
    protected String podmiotOdpowiedzialnyNazwa;
    @XmlElement(name = "podmiot-odpowiedzialny-kraj", required = true)
    protected String podmiotOdpowiedzialnyKraj;

    /**
     * Gets the value of the idTowaru property.
     * 
     */
    public int getIdTowaru() {
        return idTowaru;
    }

    /**
     * Sets the value of the idTowaru property.
     * 
     */
    public void setIdTowaru(int value) {
        this.idTowaru = value;
    }

    /**
     * Gets the value of the idTowaruKs property.
     * 
     */
    public int getIdTowaruKs() {
        return idTowaruKs;
    }

    /**
     * Sets the value of the idTowaruKs property.
     * 
     */
    public void setIdTowaruKs(int value) {
        this.idTowaruKs = value;
    }

    /**
     * Gets the value of the nazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwa() {
        return nazwa;
    }

    /**
     * Sets the value of the nazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwa(String value) {
        this.nazwa = value;
    }

    /**
     * Gets the value of the postac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostac() {
        return postac;
    }

    /**
     * Sets the value of the postac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostac(String value) {
        this.postac = value;
    }

    /**
     * Gets the value of the dawka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDawka() {
        return dawka;
    }

    /**
     * Sets the value of the dawka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDawka(String value) {
        this.dawka = value;
    }

    /**
     * Gets the value of the opakowanie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpakowanie() {
        return opakowanie;
    }

    /**
     * Sets the value of the opakowanie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpakowanie(String value) {
        this.opakowanie = value;
    }

    /**
     * Gets the value of the stawkaVat property.
     * 
     */
    public float getStawkaVat() {
        return stawkaVat;
    }

    /**
     * Sets the value of the stawkaVat property.
     * 
     */
    public void setStawkaVat(float value) {
        this.stawkaVat = value;
    }

    /**
     * Gets the value of the pkwiu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkwiu() {
        return pkwiu;
    }

    /**
     * Sets the value of the pkwiu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkwiu(String value) {
        this.pkwiu = value;
    }

    /**
     * Gets the value of the podmiotOdpowiedzialnyNazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodmiotOdpowiedzialnyNazwa() {
        return podmiotOdpowiedzialnyNazwa;
    }

    /**
     * Sets the value of the podmiotOdpowiedzialnyNazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodmiotOdpowiedzialnyNazwa(String value) {
        this.podmiotOdpowiedzialnyNazwa = value;
    }

    /**
     * Gets the value of the podmiotOdpowiedzialnyKraj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodmiotOdpowiedzialnyKraj() {
        return podmiotOdpowiedzialnyKraj;
    }

    /**
     * Sets the value of the podmiotOdpowiedzialnyKraj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodmiotOdpowiedzialnyKraj(String value) {
        this.podmiotOdpowiedzialnyKraj = value;
    }

}
