//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.06 at 11:26:52 PM CET 
//


package com.example.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.kedi}id-zamowienia"/>
 *         &lt;element ref="{http://www.kedi}id-poz-zamowienia"/>
 *         &lt;element ref="{http://www.kedi}ilosc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "zrodlo-poz-faktury")
public class ZrodloPozFaktury {

    @XmlElement(name = "id-zamowienia")
    protected long idZamowienia;
    @XmlElement(name = "id-poz-zamowienia")
    protected int idPozZamowienia;
    protected float ilosc;

    /**
     * Gets the value of the idZamowienia property.
     * 
     */
    public long getIdZamowienia() {
        return idZamowienia;
    }

    /**
     * Sets the value of the idZamowienia property.
     * 
     */
    public void setIdZamowienia(long value) {
        this.idZamowienia = value;
    }

    /**
     * Gets the value of the idPozZamowienia property.
     * 
     */
    public int getIdPozZamowienia() {
        return idPozZamowienia;
    }

    /**
     * Sets the value of the idPozZamowienia property.
     * 
     */
    public void setIdPozZamowienia(int value) {
        this.idPozZamowienia = value;
    }

    /**
     * Gets the value of the ilosc property.
     * 
     */
    public float getIlosc() {
        return ilosc;
    }

    /**
     * Sets the value of the ilosc property.
     * 
     */
    public void setIlosc(float value) {
        this.ilosc = value;
    }

}
